[package]
name = "embedded-llm"
version = "0.0.0"
edition = "2024"
license = "CC0-1.0"
description = "LLM traits which work universally"

[dependencies]
embedded-io = "0.6.1"
embedded-io-async = "0.6.1"
futures-core = { version = "0.3.31", default-features = false }
